#!/usr/bin/env python3
"""Generate `srcs/juloo.keyboard2/staged/PinyinData.java`.

Usage (from the repository root):

    python3 -B srcs/pinyin/compile.py

Reads `srcs/pinyin/syllables.txt` (pinyin syllable, then the characters written
with it, most frequent first) and `srcs/pinyin/variants.txt` (simplified
character then its traditional variant), both built from the Unihan database by
`from_unihan.py`, and adds the Zhuyin spelling of every syllable, which is
computed here.
"""

import os
import sys

SOURCE_DIR = os.path.join("srcs", "pinyin")
OUTPUT = os.path.join("srcs", "juloo.keyboard2", "staged", "PinyinData.java")

# Bopomofo initials, longest first so that "zh" is read before "z".
INITIALS = [
    ("zh", "\u3113"), ("ch", "\u3114"), ("sh", "\u3115"),
    ("b", "\u3105"), ("p", "\u3106"), ("m", "\u3107"), ("f", "\u3108"),
    ("d", "\u3109"), ("t", "\u310a"), ("n", "\u310b"), ("l", "\u310c"),
    ("g", "\u310d"), ("k", "\u310e"), ("h", "\u310f"),
    ("j", "\u3110"), ("q", "\u3111"), ("x", "\u3112"),
    ("r", "\u3116"), ("z", "\u3117"), ("c", "\u3118"), ("s", "\u3119"),
]

# Bopomofo finals, by the pinyin spelling of the final. "v" stands for "ü".
FINALS = {
    "a": "\u311a", "o": "\u311b", "e": "\u311c", "ai": "\u311e",
    "ei": "\u311f", "ao": "\u3120", "ou": "\u3121", "an": "\u3122",
    "en": "\u3123", "ang": "\u3124", "eng": "\u3125", "er": "\u3126",
    "i": "\u3127", "ia": "\u3127\u311a", "io": "\u3127\u311b",
    "ie": "\u3127\u311d", "iai": "\u3127\u311e", "iao": "\u3127\u3120",
    "iu": "\u3127\u3121", "ian": "\u3127\u3122", "in": "\u3127\u3123",
    "iang": "\u3127\u3124", "ing": "\u3127\u3125", "iong": "\u3129\u3125",
    "u": "\u3128", "ua": "\u3128\u311a", "uo": "\u3128\u311b",
    "uai": "\u3128\u311e", "ui": "\u3128\u311f", "uan": "\u3128\u3122",
    "un": "\u3128\u3123", "uang": "\u3128\u3124", "ueng": "\u3128\u3125",
    "ong": "\u3128\u3125",
    "v": "\u3129", "ve": "\u3129\u311d", "van": "\u3129\u3122",
    "vn": "\u3129\u3123",
}

# Syllables that are not an initial followed by a final: the "y" and "w"
# spellings of a medial, and the standalone finals.
WHOLE = {
    "yi": "\u3127", "ya": "\u3127\u311a", "yo": "\u3127\u311b",
    "ye": "\u3127\u311d", "yai": "\u3127\u311e", "yao": "\u3127\u3120",
    "you": "\u3127\u3121", "yan": "\u3127\u3122", "yin": "\u3127\u3123",
    "yang": "\u3127\u3124", "ying": "\u3127\u3125", "yong": "\u3129\u3125",
    "yu": "\u3129", "yue": "\u3129\u311d", "yuan": "\u3129\u3122",
    "yun": "\u3129\u3123",
    "wu": "\u3128", "wa": "\u3128\u311a", "wo": "\u3128\u311b",
    "wai": "\u3128\u311e", "wei": "\u3128\u311f", "wan": "\u3128\u3122",
    "wen": "\u3128\u3123", "wang": "\u3128\u3124", "weng": "\u3128\u3125",
    "r": "\u3126",
}

# After these initials, "u" is written for "ü".
U_IS_UMLAUT = ("j", "q", "x")
# After these initials, the final "i" is not written.
I_IS_SILENT = ("zh", "ch", "sh", "r", "z", "c", "s")


def zhuyin(syllable):
    """The Bopomofo spelling of a toneless pinyin syllable, or None."""
    if syllable in WHOLE:
        return WHOLE[syllable]
    for initial, bopomofo in INITIALS:
        if not syllable.startswith(initial) or len(syllable) == len(initial):
            continue
        final = syllable[len(initial):]
        if initial in U_IS_UMLAUT and final.startswith("u"):
            final = "v" + final[1:]
        if initial in I_IS_SILENT and final == "i":
            final = ""
        if final == "":
            return bopomofo
        return bopomofo + FINALS[final] if final in FINALS else None
    return FINALS.get(syllable)


def read_table(name):
    """Read a file of the [SOURCE_DIR] directory, skipping the comments."""
    with open(os.path.join(SOURCE_DIR, name), encoding="utf-8") as f:
        return [line.rstrip("\n") for line in f if not line.startswith("#") and line.strip()]


def java_string(lines):
    """A Java expression for a string made of [lines], one per line."""
    if not lines:
        return '    ""'
    parts = ['"%s\\n"' % escape(line) for line in lines]
    return "    " + "\n    + ".join(parts)


def escape(s):
    return (s.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "\\t"))


TEMPLATE = '''package juloo.keyboard2.staged;

import java.util.HashMap;
import java.util.Map;

/** The characters that can be typed with the Pinyin and Zhuyin input methods.

    Generated by `srcs/pinyin/compile.py` from the tables built by
    `srcs/pinyin/from_unihan.py`. Do not edit. */
final class PinyinData
{
  /** One line per syllable: a toneless pinyin syllable, a space, then the
      characters written with it, most frequent first. */
  private static final String SYLLABLES =
%s;

  /** One line per character: a simplified character followed by its
      traditional variant. */
  private static final String VARIANTS =
%s;

  /** One line per syllable: a Zhuyin spelling, a tab, then the pinyin syllable
      it stands for. */
  private static final String ZHUYIN =
%s;

  private static final Map<String, String> _syllables = new HashMap<String, String>();
  private static final Map<String, String> _zhuyin = new HashMap<String, String>();
  private static final Map<Character, Character> _variants = new HashMap<Character, Character>();

  static
  {
    for (String line : SYLLABLES.split("\\n"))
    {
      int sep = line.indexOf(' ');
      _syllables.put(line.substring(0, sep), line.substring(sep + 1));
    }
    for (String line : VARIANTS.split("\\n"))
      _variants.put(line.charAt(0), line.charAt(1));
    for (String line : ZHUYIN.split("\\n"))
    {
      int sep = line.indexOf('\\t');
      _zhuyin.put(line.substring(0, sep), line.substring(sep + 1));
    }
  }

  /** The characters that can be typed with [syllable], most frequent first, or
      [null] when the syllable is unknown. */
  static String chars(String syllable)
  {
    return _syllables.get(syllable);
  }

  /** The pinyin syllable that the Zhuyin spelling [zhuyin] stands for, or
      [null] when the spelling is unknown. */
  static String pinyin(String zhuyin)
  {
    return _zhuyin.get(zhuyin);
  }

  /** The traditional variant of [c], or [c] itself when it has none. */
  static char traditional(char c)
  {
    Character t = _variants.get(c);
    return (t == null) ? c : t.charValue();
  }
}
'''


def main():
    syllables = read_table("syllables.txt")
    variants = read_table("variants.txt")
    spellings = []
    unmapped = []
    seen = set()
    for line in syllables:
        syllable = line.split(" ")[0]
        bopomofo = zhuyin(syllable)
        if bopomofo is None:
            unmapped.append(syllable)
        elif bopomofo in seen:
            # Two pinyin spellings of the same syllable, such as "er" and "r":
            # keep the first one, the tables are read in sorted order.
            continue
        else:
            seen.add(bopomofo)
            spellings.append(bopomofo + "\t" + syllable)
    spellings.sort()
    if unmapped:
        sys.stderr.write("Syllables without a Zhuyin spelling: %s\n"
            % ", ".join(unmapped))
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(TEMPLATE % (java_string(syllables), java_string(variants),
              java_string(spellings)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
