/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package juloo.keyboard2;

public final class R {
    public static final class array {
        public static final int pref_layout_entries=0x7f050001;
        public static final int pref_layout_values=0x7f050000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int bg=0x7f060000;
        public static final int emoji_button_bg=0x7f060009;
        public static final int emoji_color=0x7f06000a;
        public static final int emoji_key_bg=0x7f06000b;
        public static final int emoji_key_text=0x7f06000c;
        public static final int key_bg=0x7f060001;
        public static final int key_down_bg=0x7f060002;
        public static final int key_label=0x7f060003;
        public static final int key_label_locked=0x7f060004;
        public static final int key_sub_label=0x7f060005;
        public static final int preview_bg=0x7f060007;
        public static final int preview_stroke=0x7f060008;
        public static final int preview_text=0x7f060006;
    }
    public static final class dimen {
        public static final int emoji_grid_height=0x7f07000f;
        public static final int emoji_type_button_height=0x7f07000e;
        public static final int horizontal_margin=0x7f070000;
        public static final int key_bg_padding=0x7f070004;
        public static final int key_height=0x7f070005;
        public static final int key_padding=0x7f070003;
        public static final int key_round=0x7f070006;
        public static final int label_text_size=0x7f070007;
        public static final int margin_bottom=0x7f070002;
        public static final int margin_top=0x7f070001;
        public static final int preview_corners=0x7f07000a;
        public static final int preview_margin=0x7f07000c;
        public static final int preview_padding=0x7f07000d;
        public static final int preview_stroke=0x7f07000b;
        public static final int preview_text=0x7f070009;
        public static final int sublabel_text_size=0x7f070008;
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
        public static final int preview_popup=0x7f020001;
    }
    public static final class id {
        public static final int emoji_grid=0x7f0a0000;
    }
    public static final class layout {
        public static final int emoji_pane=0x7f030000;
        public static final int keyboard=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f080000;
        public static final int pref_category_layout=0x7f080002;
        public static final int pref_category_preview=0x7f080018;
        public static final int pref_category_style=0x7f080011;
        public static final int pref_category_typing=0x7f080005;
        public static final int pref_category_vibrate=0x7f08000c;
        public static final int pref_horizontal_margin_summary=0x7f080017;
        public static final int pref_horizontal_margin_title=0x7f080016;
        public static final int pref_key_height_summary=0x7f080015;
        public static final int pref_key_height_title=0x7f080014;
        public static final int pref_layout_summary=0x7f080004;
        public static final int pref_layout_title=0x7f080003;
        public static final int pref_long_interval_summary=0x7f08000b;
        public static final int pref_long_interval_title=0x7f08000a;
        public static final int pref_long_timeout_summary=0x7f080009;
        public static final int pref_long_timeout_title=0x7f080008;
        public static final int pref_margin_bottom_summary=0x7f080013;
        public static final int pref_margin_bottom_title=0x7f080012;
        public static final int pref_preci_summary=0x7f080007;
        public static final int pref_preci_title=0x7f080006;
        public static final int pref_preview_summary=0x7f08001a;
        public static final int pref_preview_title=0x7f080019;
        public static final int pref_vibrate_duration_summary=0x7f080010;
        public static final int pref_vibrate_duration_title=0x7f08000f;
        public static final int pref_vibrate_summary=0x7f08000e;
        public static final int pref_vibrate_title=0x7f08000d;
        public static final int settings_activity_label=0x7f080001;
    }
    public static final class style {
        public static final int emojiKeyButton=0x7f090001;
        public static final int emojiTypeButton=0x7f090000;
    }
    public static final class xml {
        public static final int azerty=0x7f040000;
        public static final int method=0x7f040001;
        public static final int numeric=0x7f040002;
        public static final int qwerty=0x7f040003;
        public static final int settings=0x7f040004;
    }
}
